[build]
  command = "npm run build"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Это правило обеспечивает, что все запросы будут перенаправлены на index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 